spring:
  rabbitmq:
    host: 127.0.0.1
    port: 15672
    username: guest
    password: guest
  # 邮箱配置
#  mail:
#    host: smtp.qq.com
#    username: dbnuowork@qq.com
#    password: xxxxxxxxxxxx
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#  boot:
#    admin:
#      notify:
#        mail:
#          # 启用邮件通知
#          enabled: true
#          # 以逗号分隔的邮件收件人列表
#          to: dbnuo@foxmail.com
#          from: ${spring.mail.username}

# 日志设置
logging:
  level:
    root: info
  path: /data/logs/spring/admin
  file:
    max-history: 90

server:
  tomcat:
    accesslog:
      directory: /data/logs/spring/admin
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
